services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"   # MQTT TCP
      - "9001:9001"   # MQTT over WebSockets (optional)
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped

  mqttcli:
    image: efrecon/mqtt-client
    depends_on:
      - mosquitto
