package pipeline:transform@0.1.0;

interface transform {
    use pipeline:types/types.{envelope, process-result};
    
    process: func(input: envelope) -> process-result;
}

world transform-node {
    import pipeline:types/types;
    
    export pipeline:node/lifecycle;
    export transform;
}
