# Build all Rust plugins
build-rust: build-math-plugin

# Build the advanced math plugin (with wasm-bindgen)
build-math-plugin:
    @echo "Building advanced Rust math plugin..."
    @cd math_plugin && \
    cargo build --target wasm32-unknown-unknown --release
    @echo "Copying WASM file to plugins folder..."
    @cp math_plugin/target/wasm32-unknown-unknown/release/math_plugin.wasm ../../plugins/rust_math_plugin.wasm


# Run cargo check on all Rust plugins
check:
    @cd math_plugin && cargo check

# Format all Rust code
fmt:
    @cd math_plugin && cargo fmt

# Clean all Rust build artifacts
clean:
    @cd math_plugin && cargo clean
    @rm -rf math_plugin/pkg/
