"""WAFER threshold-filter plugin — Python polyglot demo.

Demonstrates that the same WIT filter-node contract can be implemented in Python
using componentize-py. Data scientists can write WAFER plugins without learning Rust.

Implements the filter-node world:
  - lifecycle.validate(config) → None (always valid)
  - lifecycle.init(config) → Ok(())
  - lifecycle.close() → no-op
  - filter.evaluate(input) → Ok(bool)

Config format (JSON):
  {"field": "temperature", "min": 0.0, "max": 100.0}
"""

import json
from typing import Optional

# These types are generated by componentize-py from the WIT contracts
from pipeline.node.lifecycle import Guest as LifecycleGuest
from pipeline.node.filter import Guest as FilterGuest
from pipeline.types.types import Message, ProcessError


class ThresholdFilter(LifecycleGuest, FilterGuest):
    """Threshold filter: passes messages where a numeric field is within [min, max]."""

    def __init__(self):
        self.field = "value"
        self.min_val = float("-inf")
        self.max_val = float("inf")

    def validate(self, config) -> Optional[str]:
        """Validate config without side effects."""
        if config.config:
            try:
                cfg = json.loads(config.config)
                if "field" not in cfg:
                    return "missing 'field' in config"
            except json.JSONDecodeError as e:
                return f"invalid JSON config: {e}"
        return None

    def init(self, config):
        """Initialize with parsed config."""
        if config.config:
            cfg = json.loads(config.config)
            self.field = cfg.get("field", "value")
            self.min_val = cfg.get("min", float("-inf"))
            self.max_val = cfg.get("max", float("inf"))

    def close(self):
        """Nothing to clean up."""
        pass

    def evaluate(self, input: Message) -> bool:
        """Evaluate whether the message's field is within threshold bounds."""
        payload = input.payload.read_all()
        if not payload:
            raise ProcessError.bad_input("empty payload")

        try:
            text = bytes(payload).decode("utf-8")
        except UnicodeDecodeError:
            raise ProcessError.bad_input("payload is not valid UTF-8")

        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            raise ProcessError.bad_input("payload is not valid JSON")

        if self.field not in data:
            raise ProcessError.bad_input(f"field '{self.field}' not found in payload")

        value = data[self.field]
        if not isinstance(value, (int, float)):
            raise ProcessError.bad_input(f"field '{self.field}' is not numeric")

        return self.min_val <= value <= self.max_val
